version: '3'

services:
  database:
    image: mysql:5.7
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    env_file: ./adjust/.env
    volumes:
      - .docker-cache/mysql_import:/docker-entrypoint-initdb.d
      - .docker-cache/mysql.conf.d:/etc/mysql/mysql.conf.d
      - .docker-cache/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file: ./adjust/.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - database