# Generated by Django 3.0.4 on 2020-03-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('channel', models.CharField(blank=True, max_length=128)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('os', models.CharField(blank=True, max_length=128)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('installs', models.IntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
    ]
